name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Setup env
        run: |
          cat << EOF > .env
          REACT_APP_FIREBASE_DOMAIN="igo-stats.firebaseapp.com"
          REACT_APP_FIREBASE_DATABASE="https://igo-stats-default-rtdb.europe-west1.firebasedatabase.app"
          REACT_APP_FIREBASE_PROJECT_ID="igo-stats"
          REACT_APP_FIREBASE_STORAGE_BUCKET="go-stats.appspot.com"
          REACT_APP_FIREBASE_SENDER_ID="727682889081"
          REACT_APP_FIREBASE_APP_ID="1:727682889081:web:3d6d7d1ff37c4051116ba8"
          REACT_APP_FIREBASE_LOCATION_ID="europe-west"
          REACT_APP_FIREBASE_KEY=${{ secrets.FIREBASE_KEY }}
          REACT_APP_FIREBASE_MEASUREMENT_ID="G-JJTCTHS2Q3"
          REACT_APP_GOOGLE_CLIENT_ID="727682889081-hh34u2nugkncotpdl9n2tm6n8tfgbk6a.apps.googleusercontent.com"
          EOF
      - name: Build
        run: pnpm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          REACT_APP_FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}